import BalancedAssortments.CookLevinStackTypedCorrect

/-! Kernel-executed regressions for the exact generated byte stream. -/
namespace BalancedAssortments.CookLevin.StackTableau.Examples
open NPCNF NPMachine

def acceptingMachine : Machine := ⟨0,0,0,fun _ => true,[]⟩
def rejectingMachine : Machine := ⟨0,0,0,fun _ => false,[]⟩
def emptyAssignment (n : ℕ) : Bool := decide (n∈([0,1,4] : List ℕ))
def paddedAssignment (n : ℕ) : Bool := decide (n∈([0,1,3,7,12,14,18,21,24,26,30,33,34] : List ℕ))

#guard formulaEval emptyAssignment (raw acceptingMachine [] 0).decode.formula
#guard !formulaEval emptyAssignment (raw rejectingMachine [] 0).decode.formula
#guard formulaEval paddedAssignment (raw acceptingMachine [true] 1).decode.formula
#guard (Encoding.parse (StackBuilder.value (program acceptingMachine)
  (StackInitialize.scalarEnv acceptingMachine [] 0) (StackInitialize.specStore acceptingMachine [] 0))).1 =
    some (raw acceptingMachine [] 0)

end BalancedAssortments.CookLevin.StackTableau.Examples
