import BalancedAssortments.CookLevinStackTableauProgram
import BalancedAssortments.CookLevinStackTypedCorrect
import BalancedAssortments.CookLevinStackTypedValid

/-! Unconditional operational Cook–Levin reduction. Its output is generated by
finite Boolean-stack instructions with a polynomial primitive clock; both the
raw grammar and satisfiability are proved for that exact emitted bit stream. -/
noncomputable section
namespace BalancedAssortments.CookLevin.StackTableau
open NPCNF NPMachine NPStack
open StackInitialize.InitializedBuilder

theorem output_correct (M : Machine) (e : FuelExpr) (word : List Bool) :
    Encoding.CNFLanguage (output M e (program M) word) ↔
      AcceptsWithin M word (e.polynomial.eval word.length) := by
  unfold output
  rw [program_raw,Encoding.CNFLanguage_encode,and_iff_right (raw_valid M word _)]
  exact raw_satisfiable_iff M word _

/-- Every conventional polynomial-clock one-tape nondeterministic language
reduces to the total binary CNF language by an actual finite deterministic
polynomial-time transducer. No polynomial-cost annotation is used as code. -/
theorem np_to_cnf (L : Set (List Bool)) (hL : InNP L) :
    PolyManyOne L {bits | Encoding.CNFLanguage bits} := by
  obtain ⟨M,p,h⟩ := hL
  obtain ⟨e,he⟩ := polynomial_has_fuel_program p
  refine ⟨output M e (program M),⟨tableauPolynomialProgram M e⟩,?_⟩
  intro word
  change word∈L ↔ Encoding.CNFLanguage (output M e (program M) word)
  rw [output_correct,he]
  exact h word
end BalancedAssortments.CookLevin.StackTableau
