import BalancedAssortments.FixedSupportAlgorithmBreakpoints

namespace BalancedAssortments.FixedSupportAlgorithm

section OrderedField
variable {𝕜 : Type*} [Field 𝕜] [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜]
variable {ι : Type*} [Fintype ι]

def clippedObjective (base : 𝕜) (weight : ι → 𝕜) (active : ι → Bool)
    (cap residual : ι → Affine (𝕜 := 𝕜)) (t : 𝕜) : 𝕜 :=
  base * t + ∑ i, weight i * (if active i then
    min (affineValue (cap i) t) (max (affineValue (residual i) t) 0) else 0)

/-- Exact finite maximization for the piecewise-affine objective generated by
continuous-knapsack prefix formulas on one attraction-cap interval. The only
required roots are residual-before and residual-after-capacity roots. -/
theorem clippedObjective_endpoint (base : 𝕜) (weight : ι → 𝕜) (active : ι → Bool)
    (cap residual : ι → Affine (𝕜 := 𝕜)) {lo hi x : 𝕜} (D : Finset 𝕜)
    (hlo : lo ∈ D) (hhi : hi ∈ D) (hD : ∀ t ∈ D, lo ≤ t ∧ t ≤ hi)
    (hx : lo ≤ x ∧ x ≤ hi)
    (hc : ∀ i t, lo ≤ t → t ≤ hi → 0 ≤ affineValue (cap i) t)
    (hroot : ∀ i, (residual i).1 ≠ 0 →
      lo ≤ affineRoot (residual i) → affineRoot (residual i) ≤ hi → affineRoot (residual i) ∈ D)
    (hrootAfter : ∀ i, (residual i).1 - (cap i).1 ≠ 0 →
      lo ≤ affineRoot ((residual i).1 - (cap i).1, (residual i).2 - (cap i).2) →
      affineRoot ((residual i).1 - (cap i).1, (residual i).2 - (cap i).2) ≤ hi →
      affineRoot ((residual i).1 - (cap i).1, (residual i).2 - (cap i).2) ∈ D) :
    ∃ t ∈ D, clippedObjective base weight active cap residual x ≤
      clippedObjective base weight active cap residual t := by
  classical
  obtain ⟨a, ha, b, hb, hax, hxb, hgap⟩ := exists_adjacent_bracket hlo hhi hx
  have had := hD a ha
  have hbd := hD b hb
  have hbefore (i : ι) : (residual i).1 ≠ 0 →
      ¬(a < affineRoot (residual i) ∧ affineRoot (residual i) < b) := by
    intro hn ⟨hal, hbr⟩
    have hm := hroot i hn (had.1.trans hal.le) (hbr.le.trans hbd.2)
    rcases hgap _ hm with hh | hh <;> linarith
  have hafter (i : ι) : (residual i).1 - (cap i).1 ≠ 0 →
      ¬(a < affineRoot ((residual i).1 - (cap i).1, (residual i).2 - (cap i).2) ∧
        affineRoot ((residual i).1 - (cap i).1, (residual i).2 - (cap i).2) < b) := by
    intro hn ⟨hal, hbr⟩
    have hm := hrootAfter i hn (had.1.trans hal.le) (hbr.le.trans hbd.2)
    rcases hgap _ hm with hh | hh <;> linarith
  have hex : ∀ i, ∃ f : Affine (𝕜 := 𝕜), ∀ t, a ≤ t → t ≤ b →
      (if active i then min (affineValue (cap i) t) (max (affineValue (residual i) t) 0) else 0) =
        affineValue f t := by
    intro i
    cases hi : active i
    · refine ⟨(0, 0), ?_⟩
      intro t _ _
      simp [hi, affineValue]
    · obtain ⟨f, hf⟩ := clipped_affine_piece
        (fun t hat htb => hc i t (had.1.trans hat) (htb.trans hbd.2)) (hbefore i) (hafter i)
      exact ⟨f, fun t hat htb => by simpa [hi] using hf t hat htb⟩
  choose f hf using hex
  let q : Affine (𝕜 := 𝕜) := (base + ∑ i, weight i * (f i).1, ∑ i, weight i * (f i).2)
  have heval (t : 𝕜) (hat : a ≤ t) (htb : t ≤ b) :
      clippedObjective base weight active cap residual t = affineValue q t := by
    unfold clippedObjective
    rw [Finset.sum_congr rfl (fun i _ => congrArg (fun u => weight i * u) (hf i t hat htb))]
    rw [affine_weighted_sum]
    dsimp [q, affineValue]
    ring
  have hmax := affine_endpoint_max q ⟨hax, hxb⟩
  have hab : a ≤ b := hax.trans hxb
  rw [← heval x hax hxb, ← heval a le_rfl hab, ← heval b hab le_rfl] at hmax
  by_cases hh : clippedObjective base weight active cap residual a ≤
      clippedObjective base weight active cap residual b
  · exact ⟨b, hb, by simpa [max_eq_right hh] using hmax⟩
  · exact ⟨a, ha, by simpa [max_eq_left (le_of_not_ge hh)] using hmax⟩

end OrderedField
end BalancedAssortments.FixedSupportAlgorithm
