import BalancedAssortments.FPTASGuarantee
#print axioms BalancedAssortments.FPTAS.runSales_approximation
#print axioms BalancedAssortments.FPTAS.runPolicy_approximation
#print axioms BalancedAssortments.FPTAS.runPolicy_valid
