import BalancedAssortments.NPSATSubsetSumReductionCost
import BalancedAssortments.FPTASCostFlatGuarantee
#print axioms BalancedAssortments.NPSATSubsetSum.total_three_sat_reduction
#print axioms BalancedAssortments.FPTASCostCodec.flat_policy_fptas
